title: Mahesh Tom # your name (or website title) here
logo: "/images/photo_mahesh.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MTech (Research) student,
  <br>
  Computational and Mathematics Group(CMG),
  <br>
  Department of Computational and Data Sciences
  <br>
  Indian Instute of Science
  <br><br>
  <a href="https://www.linkedin.com/in/mahesh-tom-007802113">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
